### ISSUE TITLE
Radio buttons on select music page not vertically aligned

### ISSUE THREAD

**Issue by dwilliams27** [ColemanMitch/Spowerfy-Redux#10]
No idea whats up with them, the `margin-top` value gets dynamically changed as you resize, but its changed to the WRONG value. I suck at css lol

**Comment by ColemanMitch** [comment]
Bro same, I got them to look good on my screen and called it day 😅

**Comment by dwilliams27** [comment]
yeah with like certain screen sizes they _are_ centered, but that's like LITERALLY the prime example of a broken clock is right twice a day 😂

**Comment by ColemanMitch** [comment]
I removed the radio buttons on this PR #15
