### ISSUE TITLE
Having trouble logging in with in a non-incognito/private browser

### ISSUE THREAD

**Issue by ColemanMitch** [ColemanMitch/Spowerfy-Redux#20]
Might have to do with me already being logged into my Spotify account already in my web browser, but for whaterver reason I can only get past the log in screen in a private window... curious to know if that's also the case for you @dwilliams27 

Screen recording of what I'm experiencing:

https://user-images.githubusercontent.com/44789534/163428112-3398c862-11e0-474e-aaa6-f1b66078a653.mov

**Comment by dwilliams27** [comment]
Oh weird; hmm I wasnt having this yesterday

**Comment by dwilliams27** [comment]
Yeah just tried latest off of main after merging in my PR and I still get redirected properly; I assume you've exported proper spotify client and secret ID before running backend?

**Comment by ColemanMitch** [comment]
> Oh weird; hmm I wasnt having this yesterday

Word. I think have something to do with the cache in my browser... I'm gonna continue to dig on this bug and see what I can find out

**Comment by ColemanMitch** [comment]
> Yeah just tried latest off of main after merging in my PR and I still get redirected properly; I assume you've exported proper spotify client and secret ID before running backend?

Yep, I have both the client and secret ID exported in my terminal running the BE. It's bizarre to me that it works in incognito and not a regular browser

**Comment by dwilliams27** [comment]
You try clearing entire cache? Almost every time at work when incognito works but regular doesnt its some caching bs

**Comment by dwilliams27** [comment]
Could try another browser too, would confirm cache issue

**Comment by ColemanMitch** [comment]
Lmao it was my [browser extension](https://privacybadger.org/) that was blocking the authentication request 😭
