### ISSUE TITLE
Prod app access issue

### ISSUE THREAD

**Issue by ColemanMitch** [ColemanMitch/Spowerfy-Redux#29]
Spotify recently changed access for 3rd party apps that use their API such that you can only have a max of 25 authorized users on a given app (unless you request an extension). 

![image](https://user-images.githubusercontent.com/44789534/164734534-7d672d2f-f726-4606-b64f-ff914bf81694.png)

@dwilliams27 can you confirm that you can log in and use the app on the "prod" environment?

**Comment by dwilliams27** [comment]
Ayee it works now
