### ISSUE TITLE
Switching an active playback from one device to another

### ISSUE THREAD

**Issue by ColemanMitch** [ColemanMitch/Spowerfy-Redux#4]
The playback gets a bit confused when I try to switch devices with an active playback already going. 

Steps to recreate bug:
1. Start playing Spotify on phone
2. Open Spotify on another device (laptop or smart speaker)
3. Open Spowerfy on your laptop 
3. Configure playback to a different device (other than phone) from dropdown and select any playlist
4. Click the start button and observe (it takes about 3-4 songs for Spowerfy to "catch up" and display an accurate playback)

**Comment by dwilliams27** [comment]
On it boss

**Comment by ColemanMitch** [comment]
Playback is switching properly now between devices and playlists. However, the album art, song title, and artist is only updating correctly like ~50% of the time when it skips to the next song

**Comment by ColemanMitch** [comment]
Closing this issue with #11 merged into `main`
