### ISSUE TITLE
Configurable Timer interval slider 

### ISSUE THREAD

**Issue by ColemanMitch** [ColemanMitch/Spowerfy-Redux#5]
I'm thinking that we could implement a feature where a user is able to configure the interval (15s - 90s) in between songs with a [slider](https://material-ui.com/components/slider/).

And in terms of where we could put the slider, I'm thinking that it could go on the right side of the screen (see image) and we could push the device dropdown and playlist search bar to take up the left half of the screen. Let me know what your thoughts are @dwilliams27 

![image](https://user-images.githubusercontent.com/44789534/111637470-75d3f980-87c7-11eb-9840-800d262e393c.png)

**Comment by dwilliams27** [comment]
Yeah agreed a slider there for this sounds good. Probably need to think of where it would look good besides just floating to the right, like was thinking maybe we center the text in the upper left and then add this above the device select dropdown or smth. Might also want to be able to change the timing once the power hour has started, so maybe add that slider on that screen too

**Comment by ColemanMitch** [comment]
I kinda dig that more tbh. It'll look way better on most screens. Let's pivot to center aligning everything!!

**Comment by ColemanMitch** [comment]
Hey @dwilliams27, the configurable interval slider is just on the partyStarted screen. I wasn't sure how to best integrate it onto the Music Select screen
